// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtrao4sb6ilCE5XmJtT_ajjrcqxD___Ng',
    appId: '1:713478415507:web:cab33b6eb1be2ea2449966',
    messagingSenderId: '713478415507',
    projectId: 'instagram-clone-44c53',
    authDomain: 'instagram-clone-44c53.firebaseapp.com',
    storageBucket: 'instagram-clone-44c53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxGd4gU99SUHjuluSrcnrI8xllxWDklJg',
    appId: '1:713478415507:android:4892586f193117f5449966',
    messagingSenderId: '713478415507',
    projectId: 'instagram-clone-44c53',
    storageBucket: 'instagram-clone-44c53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR4mPaQkOESzb2tEE6nQRP75I1ZwFg9-k',
    appId: '1:713478415507:ios:678b39daf23c59d2449966',
    messagingSenderId: '713478415507',
    projectId: 'instagram-clone-44c53',
    storageBucket: 'instagram-clone-44c53.firebasestorage.app',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR4mPaQkOESzb2tEE6nQRP75I1ZwFg9-k',
    appId: '1:713478415507:ios:678b39daf23c59d2449966',
    messagingSenderId: '713478415507',
    projectId: 'instagram-clone-44c53',
    storageBucket: 'instagram-clone-44c53.firebasestorage.app',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtrao4sb6ilCE5XmJtT_ajjrcqxD___Ng',
    appId: '1:713478415507:web:7285decb23bac90f449966',
    messagingSenderId: '713478415507',
    projectId: 'instagram-clone-44c53',
    authDomain: 'instagram-clone-44c53.firebaseapp.com',
    storageBucket: 'instagram-clone-44c53.firebasestorage.app',
  );
}
